using cAlgo.API;

namespace cAlgo.Robots;

public class ExtractedParameters
{
    public string Version { get; set; }
    public bool InputShowLineLabels { get; set; }
    public bool InputShowAdditionalStopLossLabel { get; set; }
    public bool InputShowAdditionalTpLabel { get; set; }
    public bool InputShowAdditionalEntryLabel { get; set; }
    public bool InputHideAccountSize { get; set; }
    public bool InputShowPipValue { get; set; }
    public bool InputShowMaxPositionSizeButton { get; set; }
    public bool InputStartPanelMinimized { get; set; }
    public bool InputShowAtrOptions { get; set; }
    public bool InputShowMaxParametersOnTradingTab { get; set; }
    public bool InputShowTradingFusesOnTradingTab { get; set; }
    public bool InputShowCheckBoxesOnTradingTab { get; set; }
    public AdditionalTradeButtons InputAdditionalTradeButtons { get; set; }
    public bool InputHideEntryLineForInstantOrders { get; set; }
    public SerializableColor InputStopLossLabelColor { get; set; }
    public SerializableColor InputTpLabelColor { get; set; }
    public SerializableColor InputStopPriceLabelColor { get; set; }
    public SerializableColor InputEntryLabelColor { get; set; }
    public int InputLabelsFontSize { get; set; }
    public SerializableColor InputEntryLineColor { get; set; }
    public SerializableColor InputStopLossLineColor { get; set; }
    public SerializableColor InputTakeProfitLineColor { get; set; }
    public SerializableColor InputStopPriceLineColor { get; set; }
    public SerializableColor InputBreakevenLineColor { get; set; }
    public LineStyle InputEntryLineStyle { get; set; }
    public LineStyle InputStopLossLineStyle { get; set; }
    public LineStyle InputTakeProfitLineStyle { get; set; }
    public LineStyle InputStopPriceLineStyle { get; set; }
    public LineStyle InputBreakevenLineStyle { get; set; }
    public int InputEntryLineWidth { get; set; }
    public int InputStopLossLineWidth { get; set; }
    public int InputTakeProfitLineWidth { get; set; }
    public int InputStopPriceLineWidth { get; set; }
    public int InputBreakevenLineWidth { get; set; }
    public TradeType InputTradeType { get; set; }
    public double InputDefaultStopLossPips { get; set; }
    public double InputDefaultTakeProfitPips { get; set; }
    public int InputTakeProfitsNumber { get; set; }
    public OrderType InputOrderType { get; set; }
    public bool InputShowLinesByDefault { get; set; }
    public int InputAtrPeriod { get; set; }
    public double InputDefaultAtrMultiplierStopLoss { get; set; }
    public double InputDefaultAtrMultiplierTakeProfit { get; set; }
    public SerializableTimeFrame InputAtrTimeFrame { get; set; }
    public bool InputSpreadAdjustmentStopLoss { get; set; }
    public bool InputSpreadAdjustmentTakeProfit { get; set; }
    public AccountSizeMode InputAccountSizeMode { get; set; }
    public double InputRiskPercentage { get; set; }
    public double InputMoneyRisk { get; set; }
    public double InputPositionSizeInLots { get; set; }
    public IncludeOrdersMode InputIncludeOrdersMode { get; set; }
    public bool InputIgnoreOrdersWithoutStopLoss { get; set; }
    public bool InputIgnoreOrdersWithoutTakeProfit { get; set; }
    public IncludeSymbolsMode InputIncludeSymbolsMode { get; set; }
    public IncludeDirectionsMode InputIncludeDirectionsMode { get; set; }
    public double InputCustomLeverage { get; set; }
    public string InputLabel { get; set; }
    public string InputCommentary { get; set; }
    public bool InputAutoSuffix { get; set; }
    public bool InputDisableTradingWhenLinesAreHidden { get; set; }
    public double InputMaxSlippagePips { get; set; }
    public double InputMaxSpreadPips { get; set; }
    public double InputMaxEntryStopLossDistancePips { get; set; }
    public double InputMinEntryStopLossDistancePips { get; set; }
    public double InputMaxPositionSizeTotalForTradingTab { get; set; }
    public double InputMaxPositionSizePerSymbolForTradingTab { get; set; }
    public bool InputSubtractOpv { get; set; }
    public bool InputSubtractPov { get; set; }
    public bool InputDoNotApplyStopLoss { get; set; }
    public bool InputDoNotApplyTakeProfit { get; set; }
    public bool InputAskForConfirmation { get; set; }
    public int InputPanelPositionX { get; set; }
    public int InputPanelPositionY { get; set; }
    public bool InputTakeProfitLockedOnStopLoss { get; set; }
    public double InputTrailingStopPips { get; set; }
    public double InputBreakevenPips { get; set; }
    public int InputExpirySeconds { get; set; }
    public int InputMaxNumberOfTradesTotal { get; set; }
    public int InputMaxNumberOfTradesPerSymbol { get; set; }
    public double InputMaxRiskTotal { get; set; }
    public double InputMaxRiskPerSymbol { get; set; }
    public bool InputStopLossDistancePipsInsteadOfLevel { get; set; }
    public bool InputTakeProfitDistancePipsInsteadOfLevel { get; set; }
    public string InputHotkeyExecuteTrade { get; set; }
    public string InputHotkeySwitchOrderType { get; set; }
    public string InputHotkeySwitchEntryDirection { get; set; }
    public string InputHotkeySwitchHideShowLines { get; set; }
    public string InputHotkeySetStopLoss { get; set; }
    public string InputHotkeySetTakeProfit { get; set; }
    public string InputHotkeySetEntry { get; set; }
    public string InputMinimizeMaximizeHotkeyPanel { get; set; }
    public string InputHotkeySwitchStopLossPointsLevel { get; set; }
    public string InputSwitchTpPointsLevelHotkey { get; set; }
    public double InputTakeProfitMultiplierForStopLossValue { get; set; }
    public bool InputUseCommissionToSetTpDistance { get; set; }
    public ShowSpreadMode InputShowSpread { get; set; }
    public double InputAdditionalFunds { get; set; }
    public double InputCustomBalance { get; set; }
    public AtrCandle InputAtrCandle { get; set; }
    public bool InputCalculateUnadjustedPositionSize { get; set; }
    public bool InputSurpassBrokerMaxPositionSizeWithMultipleTrades { get; set; }
    public bool InputUseAsyncOrders { get; set; }
    public RoundingMode InputRoundingPositionSizeAndPotentialReward { get; set; }
    public double InputQuickRisk1Pct { get; set; }
    public double InputQuickRisk2Pct { get; set; }
    public bool InputDisableStopLimit { get; set; }
    public bool InputApplySlTpAfterAllTradesExecuted { get; set; }
    public bool InputDarkMode { get; set; }
    public bool InputRestoreWindowLocationOnChartSizeChange { get; set; }
    public bool InputUseLastSavedSettings { get; set; }
    public bool InputPrefillAdditionalTpsBasedOnMain { get; set; }
    public bool InputAskForConfirmationBeforeClosingThePanel { get; set; }
    public bool InputAllowSmallerTradesWhenTradingLimitsAreExceeded { get; set; }
    public int InputRefreshMilliseconds { get; set; }
    public int InputIndexTest { get; set; }
}